name: whatsapp_bulk_sender
description: A simple WhatsApp bulk sender app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.7

flutter:
  uses-material-design: true
